// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: proto/dns.proto

package dns

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DnsService_AddDnsServer_FullMethodName    = "/dns.DnsService/AddDnsServer"
	DnsService_RemoveDnsServer_FullMethodName = "/dns.DnsService/RemoveDnsServer"
	DnsService_ListDnsServers_FullMethodName  = "/dns.DnsService/ListDnsServers"
)

// DnsServiceClient is the client API for DnsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DnsServiceClient interface {
	AddDnsServer(ctx context.Context, in *AddDnsServerRequest, opts ...grpc.CallOption) (*DnsResponse, error)
	RemoveDnsServer(ctx context.Context, in *RemoveDnsServerRequest, opts ...grpc.CallOption) (*DnsResponse, error)
	ListDnsServers(ctx context.Context, in *ListDnsServersRequest, opts ...grpc.CallOption) (*ListDnsServersResponse, error)
}

type dnsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDnsServiceClient(cc grpc.ClientConnInterface) DnsServiceClient {
	return &dnsServiceClient{cc}
}

func (c *dnsServiceClient) AddDnsServer(ctx context.Context, in *AddDnsServerRequest, opts ...grpc.CallOption) (*DnsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DnsResponse)
	err := c.cc.Invoke(ctx, DnsService_AddDnsServer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dnsServiceClient) RemoveDnsServer(ctx context.Context, in *RemoveDnsServerRequest, opts ...grpc.CallOption) (*DnsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DnsResponse)
	err := c.cc.Invoke(ctx, DnsService_RemoveDnsServer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dnsServiceClient) ListDnsServers(ctx context.Context, in *ListDnsServersRequest, opts ...grpc.CallOption) (*ListDnsServersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDnsServersResponse)
	err := c.cc.Invoke(ctx, DnsService_ListDnsServers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DnsServiceServer is the server API for DnsService service.
// All implementations must embed UnimplementedDnsServiceServer
// for forward compatibility.
type DnsServiceServer interface {
	AddDnsServer(context.Context, *AddDnsServerRequest) (*DnsResponse, error)
	RemoveDnsServer(context.Context, *RemoveDnsServerRequest) (*DnsResponse, error)
	ListDnsServers(context.Context, *ListDnsServersRequest) (*ListDnsServersResponse, error)
	mustEmbedUnimplementedDnsServiceServer()
}

// UnimplementedDnsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDnsServiceServer struct{}

func (UnimplementedDnsServiceServer) AddDnsServer(context.Context, *AddDnsServerRequest) (*DnsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddDnsServer not implemented")
}
func (UnimplementedDnsServiceServer) RemoveDnsServer(context.Context, *RemoveDnsServerRequest) (*DnsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveDnsServer not implemented")
}
func (UnimplementedDnsServiceServer) ListDnsServers(context.Context, *ListDnsServersRequest) (*ListDnsServersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDnsServers not implemented")
}
func (UnimplementedDnsServiceServer) mustEmbedUnimplementedDnsServiceServer() {}
func (UnimplementedDnsServiceServer) testEmbeddedByValue()                    {}

// UnsafeDnsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DnsServiceServer will
// result in compilation errors.
type UnsafeDnsServiceServer interface {
	mustEmbedUnimplementedDnsServiceServer()
}

func RegisterDnsServiceServer(s grpc.ServiceRegistrar, srv DnsServiceServer) {
	// If the following call panics, it indicates UnimplementedDnsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DnsService_ServiceDesc, srv)
}

func _DnsService_AddDnsServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddDnsServerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DnsServiceServer).AddDnsServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DnsService_AddDnsServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DnsServiceServer).AddDnsServer(ctx, req.(*AddDnsServerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DnsService_RemoveDnsServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveDnsServerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DnsServiceServer).RemoveDnsServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DnsService_RemoveDnsServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DnsServiceServer).RemoveDnsServer(ctx, req.(*RemoveDnsServerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DnsService_ListDnsServers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDnsServersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DnsServiceServer).ListDnsServers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DnsService_ListDnsServers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DnsServiceServer).ListDnsServers(ctx, req.(*ListDnsServersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DnsService_ServiceDesc is the grpc.ServiceDesc for DnsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DnsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dns.DnsService",
	HandlerType: (*DnsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddDnsServer",
			Handler:    _DnsService_AddDnsServer_Handler,
		},
		{
			MethodName: "RemoveDnsServer",
			Handler:    _DnsService_RemoveDnsServer_Handler,
		},
		{
			MethodName: "ListDnsServers",
			Handler:    _DnsService_ListDnsServers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/dns.proto",
}
